# Generated by Django 5.1.7 on 2025-05-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Account",
            "0002_customuser_is_email_verified_alter_customuser_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
