# Generated by Django 5.1.3 on 2025-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics"),
        ),
    ]
