# Generated by Django 5.1.7 on 2025-04-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0005_alter_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="location",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="birth_date",
            new_name="dob",
        ),
        migrations.RenameField(
            model_name="userprofile",
            old_name="image",
            new_name="profile_image",
        ),
    ]
