# Generated by Django 5.1.7 on 2025-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0006_rename_location_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(default="default.jpg", upload_to="profile_pics/"),
        ),
    ]
